package ru.hadron.rec.others

object Constants {

    const val REQUEST_CODE_WR_STORAGE_RECORD_AUDIO_PERMISSIONS = 0

    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"

    const val ACTION_SHOW_RECORD_FRAGMENT = "ACTION_SHOW_RECORD_FRAGMENT"

    const val NOTIFICATION_CHANNEL_ID = "recording_channel"
    const val NOTIFICATION_CHANNEL_NAME = "recording"
    const val NOTIFICATION_ID = 1

    const val TIMER_UPDATE_INTERVAL = 50L

}